### ISSUE TITLE
Running vagrant up emdb fails

### ISSUE THREAD

**Issue by PeterHG** [biemond/biemond-em-12c-puppet4_3#1]
==> emdb: Error: /Stage[main]/Oradb_os/Package[libXtst.x86_64]/ensure: change from purged to present failed: Execution of '/bin/yum -d 0 -e 0 -y install libXtst.x86_64' returned 1: error: Failed to initialize NSS library
==> emdb: There was a problem importing one of the Python modules
==> emdb: required to run yum. The error leading to this problem was:
==> emdb: 
==> emdb:    cannot import name ts
==> emdb: 
==> emdb: Please install a package which provides this module, or
==> emdb: verify that the module is installed correctly.
==> emdb: 
==> emdb: It's possible that the above module doesn't match the
==> emdb: current version of Python, which is:
==> emdb: 2.7.5 (default, Nov 21 2015, 00:39:04) 
==> emdb: [GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

**Comment by biemond** [comment]
I see it works with centos & em 13 & 12.2 DB, maybe it is some OEL issue

can you try this
```
    emdb.vm.box = "centos-7-1611-x86_64"
    emdb.vm.box_url = "https://dl.dropboxusercontent.com/s/filvjntyct1wuxe/centos-7-1611-x86_64.box"

    emdb.vm.provider :vmware_fusion do |v, override|
      override.vm.box = "centos-7-1611-x86_64-vmware"
      override.vm.box_url = "https://dl.dropboxusercontent.com/s/6hqh2ntbiyu3srt/centos-7-1611-x86_64-vmware.box"
    end

```

**Comment by PeterHG** [comment]
That's fixed the yum install error, have you run this on OSX? Looks like it completes the database build, but ends with;

==> emdb: Info: Stage[main]: Unscheduling all events on Stage[main]
==> emdb: Info: Creating state file /opt/puppetlabs/puppet/cache/state/state.yaml
==> emdb: Notice: Applied catalog in 961.82 seconds
The SSH command responded with a non-zero exit status. Vagrant
assumes that this means the command failed. The output for this command
should be in the log above. Please read the output to determine what
went wrong.
Peters-MacBook-Pro:biemond-em-12c-puppet4_3-master PHG$
